TSV

In [1]:
import pandas as pd
import numpy as np
from models import set_models_to_wn18rr, set_models_to_family_dataset
import models
import config
import csv
import os

WARNING - All triples will be processed in the same batch (batches_count=1). When processing large graphs it is recommended to batch the input knowledge graph instead.


In [2]:
set_models_to_family_dataset()

WARNING - All triples will be processed in the same batch (batches_count=1). When processing large graphs it is recommended to batch the input knowledge graph instead.


In [25]:
transE = models.transE
distMult = models.distMult
complEx = models.complEx

In [37]:
transE.rel_to_idx

{'child': 0,
 'father': 1,
 'mother': 2,
 'relative': 3,
 'sibling': 4,
 'spouse': 5}

In [20]:
transE.trained_model_params[1][0]

array([ 2.5921036e-03, -5.1378715e-04,  6.0925673e-04, -6.4360735e-04,
       -1.1162624e-03, -1.3239661e-03, -6.2740233e-04, -8.1939751e-04,
        1.3240681e-03,  7.9619017e-04,  1.1874749e-03, -5.2318815e-03,
        1.4182774e-03,  4.6880878e-04, -5.8489437e-03, -1.3597006e-03,
       -9.0691587e-04,  1.0788145e-03, -5.8789193e-03, -4.6806870e-04,
       -4.7393597e-04, -5.6981767e-04,  3.3700101e-03,  9.4962260e-04,
       -1.6523363e-03,  4.1184444e-03, -3.8756460e-03,  5.1228413e-03,
       -7.7675737e-04,  9.3834492e-04, -1.3228742e-03,  9.6320955e-04,
       -1.5616982e-04, -9.4674021e-04,  2.0940658e-03, -2.8573934e-03,
        7.0466333e-05,  2.8148224e-04, -1.7853639e-03, -3.3151701e-03,
       -3.5839914e-03,  5.1323930e-03,  4.2408630e-03,  1.0404118e-03,
       -1.3957578e-03,  8.5631455e-04,  1.1137022e-03,  2.6401584e-03,
        5.8961246e-04,  8.3832454e-04,  1.1767243e-03, -4.8844639e-04,
        3.1180785e-04,  8.3767733e-04,  8.9519686e-04,  9.2850864e-04,
      

In [38]:
distMult.trained_model_params[1][3]

array([-1.4424584 , -0.26634935,  0.7294423 ,  0.72640395, -1.0314615 ,
        1.1091262 ,  1.3515794 , -0.7110632 ,  0.24399143,  1.1028281 ,
        1.2283919 , -1.2919731 ,  0.1429738 , -0.99629784, -0.37654164,
        0.23725276, -1.5228826 ,  1.6636608 ,  0.22007601,  1.3127974 ,
        1.0755206 , -0.19212334,  1.077906  , -0.9787266 , -1.2595278 ,
        1.4202195 ,  0.175966  , -1.0769587 , -0.36338314,  1.412147  ,
       -0.8922497 ,  1.1352404 ,  1.1352953 ,  1.07811   ,  1.1511794 ,
        1.4442632 ,  1.410017  ,  0.09672883,  0.02668649, -0.9265147 ,
        1.4314657 ,  1.1208308 ,  0.3882768 ,  0.7432494 , -1.264733  ,
        1.4030306 ,  1.7217239 ,  0.7802884 ,  1.0984806 ,  0.9740246 ,
        0.67274505,  1.2064166 , -1.8677634 , -0.33675405, -1.0044577 ,
        1.4696401 , -0.416071  ,  0.894738  ,  1.3496416 , -1.3983295 ,
        0.8882237 ,  1.2861876 ,  0.21792331,  0.8444618 , -0.7947125 ,
       -1.1850948 , -0.6438524 , -0.9140829 ,  1.7247212 ,  0.49

In [39]:
complEx.trained_model_params[1][3]

array([-1.0608493 ,  1.0451989 , -0.7379914 , -0.8482885 ,  0.8033267 ,
       -0.6440309 , -0.71236753,  0.7815177 ,  0.93258196,  0.7614581 ,
       -0.80074584,  0.4050782 ,  0.67747897,  0.7979561 , -0.59217715,
        1.0798441 ,  0.20091003,  0.04373984, -0.7604534 , -0.72807217,
       -0.89611167,  0.8706936 ,  0.3413479 ,  0.94606674,  0.7240274 ,
        0.79954445, -0.9518952 , -0.87282825, -1.0087398 , -0.12839298,
        0.94257903,  0.9683095 ,  0.8399087 ,  0.86126304, -0.99569917,
       -0.9798005 ,  0.9031811 , -0.03870657, -0.8308381 ,  0.470172  ,
       -0.7885775 ,  0.8434207 , -0.9640792 , -0.8644602 , -0.8909018 ,
       -0.7009268 ,  0.8978697 , -0.6791377 ,  0.5721034 , -0.9308221 ,
       -0.66247857,  0.75731647, -0.56328505,  0.5992958 ,  0.8696727 ,
        0.11457547,  0.72635496,  0.9059069 ,  0.85874385,  0.34039322,
       -0.99579054,  0.903529  , -0.1896702 ,  0.8483562 , -0.48781613,
       -0.9070329 , -0.8554745 ,  0.33178508,  0.9270595 ,  0.95

In [27]:
set_models_to_wn18rr()
transE_fam = models.transE
distMult_fam = models.distMult
complEx_fam = models.complEx

WARNING - All triples will be processed in the same batch (batches_count=1). When processing large graphs it is recommended to batch the input knowledge graph instead.


In [36]:
transE_fam.trained_model_params[1][0]

array([-7.18545743e-06, -5.90533164e-05, -5.79386324e-07,  3.78679797e-05,
       -2.49222485e-05, -6.64127674e-06, -6.38023776e-05,  1.31133129e-05,
       -3.42106541e-05, -2.52839491e-05, -1.77925140e-05, -5.38748172e-05,
        8.58658168e-05,  5.59104228e-06,  2.25472104e-06,  1.64239209e-05,
       -7.97239554e-05,  3.75951277e-05,  1.22559422e-05, -3.18677940e-06,
       -7.43535657e-06, -3.17616941e-05,  1.71388547e-06, -5.85004091e-06,
       -4.16300136e-05,  2.65100171e-05, -1.44062615e-05, -8.04752926e-06,
       -6.26930705e-05,  5.74955193e-05, -2.77015806e-06, -2.83978479e-05,
        1.68819461e-05,  4.09447239e-06,  3.83742008e-06,  2.42231617e-05,
       -3.38484642e-05, -9.91323759e-06,  1.40451630e-06, -5.50484328e-05,
       -9.09948358e-05,  1.62871911e-05,  2.98194627e-05,  3.69478730e-05,
        3.35928871e-06,  2.19802569e-05,  4.83385702e-06,  6.02675282e-05,
       -5.96193349e-05, -2.64154478e-05,  8.40314169e-06, -5.14838248e-05,
       -1.06441388e-04, -

In [29]:
distMult_fam.trained_model_params[1][4]

array([-1.7609967 , -1.5964977 ,  1.5261589 , -1.5625237 , -1.5662158 ,
        1.6047204 , -1.4591626 ,  1.4075942 , -1.5158284 ,  1.5277275 ,
       -1.5502623 , -0.86926425,  1.4931922 , -1.6206843 , -1.561124  ,
       -1.4710517 , -1.4539229 ,  1.5048529 , -1.5498881 ,  1.4187118 ,
        1.7232676 ,  1.143805  ,  1.6290647 ,  1.5213276 ,  1.450011  ,
        1.5434917 , -1.480198  , -1.8232231 ,  1.5218512 , -1.7504214 ,
        1.6191196 , -1.480764  , -1.4144616 ,  1.4867728 ,  1.520207  ,
       -1.7048547 ,  1.7328234 ,  1.4631455 ,  1.4035673 , -1.451357  ,
       -1.4980806 ,  1.4967777 ,  1.8748748 ,  1.5442582 , -1.6509142 ,
        1.5100605 ,  1.4352758 , -1.5056274 ,  1.5267463 , -1.737546  ,
        1.426226  ,  1.5014685 , -1.6183976 , -1.4459414 , -2.3659937 ,
       -1.4129186 , -1.6720401 ,  1.6675973 ,  1.4130979 , -1.3931391 ,
        1.4052284 , -1.537464  , -1.5502143 ,  1.5963603 ,  1.4713639 ,
       -1.5085986 , -1.4588553 ,  1.5472932 ,  1.4712323 ,  1.86

In [30]:
complEx_fam.trained_model_params[1][1]

array([-1.2787188 ,  1.3548235 , -1.1120584 ,  1.1073161 , -1.097708  ,
        1.2304591 , -1.2788582 ,  1.1764855 ,  1.0296615 ,  1.2472337 ,
       -1.2564719 , -1.1552236 , -1.0896565 ,  1.1360116 ,  1.2002006 ,
        1.1418854 ,  1.3083174 , -0.48666012,  1.2489392 ,  1.4042758 ,
        1.1401078 , -1.0627764 , -1.0667716 ,  1.3733426 ,  1.3463607 ,
       -1.3398428 ,  1.2589774 ,  1.2479371 ,  1.2985531 , -1.2151773 ,
        1.2253245 , -1.215138  , -1.3202952 ,  1.3188515 ,  1.2548696 ,
        1.1648276 ,  1.1333627 , -1.2505302 , -1.1389216 ,  1.2785536 ,
        1.4347297 , -1.220408  ,  0.26674086, -1.1587312 ,  1.14378   ,
       -1.2449958 , -0.743486  ,  1.1202585 , -1.1706322 , -1.1388826 ,
       -1.1238389 ,  1.2748727 , -1.3893218 , -1.3494804 , -0.99003226,
       -1.2130618 , -1.0928695 ,  1.1113186 ,  1.2315483 ,  1.364011  ,
        1.1626655 , -1.2898611 ,  1.3220825 ,  1.3564432 , -1.2944623 ,
       -1.233118  ,  1.211204  , -1.3601764 ,  1.3367499 ,  1.09